# Generated by Django 4.0.1 on 2022-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.TextField(db_index=True, verbose_name='Id транзакции')),
                ('data_transaction', models.DateField(auto_now_add=True, verbose_name='Дата совершения транзакции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание транзакции')),
            ],
            options={
                'ordering': ['id_transaction', '-data_transaction'],
            },
        ),
    ]
